spring:
  application:
    name: target-svc
server:
  port: 8081

debugflow:
  enabled: true    # auto-on; no POST needed
  ttlMinutes: -1   # <=0 means infinite (no expiry)
  consoleJson: false
  consolePretty: true
  color: true
  prettyFile: ../debugflow-all.log
  showThread: true
  showHttp: true
  micros: true
  simpleClassNames: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
