spring:
  application:
    name: orders-svc
server:
  port: 8082

orders:
  useTestcontainers: true

debugflow:
  enabled: true     # auto-on; no POST needed
  ttlMinutes: -1    # <=0 means infinite (no expiry)
  consoleJson: false
  consolePretty: true
  color: true
  prettyFile: ../debugflow-all.log
  showThread: true
  showHttp: true
  micros: true
  simpleClassNames: true
